//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "popupctrls_file.h"


// Declare the bitmap loading function
extern void wxCrafterpJ3MOyInitBitmapResources();

static bool bBitmapLoaded = false;


VideoCtrlPopupBase::VideoCtrlPopupBase(wxWindow* parent,long style)
    : wxPopupWindow(parent, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterpJ3MOyInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer8 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer8);
    
    m_ctrlPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer8->Add(m_ctrlPanel, 0, wxALL, 5);
    
    wxBoxSizer* boxSizer10 = new wxBoxSizer(wxVERTICAL);
    m_ctrlPanel->SetSizer(boxSizer10);
    
    m_positionctrl = new wxSlider(m_ctrlPanel, wxID_ANY, 0, 0, 100, wxDefaultPosition, wxSize(-1,-1), wxSL_HORIZONTAL);
    
    boxSizer10->Add(m_positionctrl, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer30 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer10->Add(boxSizer30, 1, wxALL|wxEXPAND, 5);
    
    wxGridSizer* gridSizer16 = new wxGridSizer(  1, 6, 0, 0);
    
    boxSizer30->Add(gridSizer16, 1, wxALL|wxEXPAND, 5);
    
    m_previousButton = new wxBitmapButton(m_ctrlPanel, wxID_ANY, wxXmlResource::Get()->LoadBitmap(wxT("control_start")), wxDefaultPosition, wxSize(-1,-1), wxBU_AUTODRAW);
    
    gridSizer16->Add(m_previousButton, 0, wxALL, 5);
    
    m_playPauseButton = new wxBitmapButton(m_ctrlPanel, wxID_ANY, wxXmlResource::Get()->LoadBitmap(wxT("control_play")), wxDefaultPosition, wxSize(-1,-1), wxBU_AUTODRAW);
    
    gridSizer16->Add(m_playPauseButton, 0, wxALL, 5);
    
    m_stopButton = new wxBitmapButton(m_ctrlPanel, wxID_ANY, wxXmlResource::Get()->LoadBitmap(wxT("control_stop")), wxDefaultPosition, wxSize(-1,-1), wxBU_AUTODRAW);
    
    gridSizer16->Add(m_stopButton, 0, wxALL, 5);
    
    m_nextButton = new wxBitmapButton(m_ctrlPanel, wxID_ANY, wxXmlResource::Get()->LoadBitmap(wxT("control_end")), wxDefaultPosition, wxSize(-1,-1), wxBU_AUTODRAW);
    
    gridSizer16->Add(m_nextButton, 0, wxALL, 5);
    
    m_toggleVideoButton = new wxBitmapButton(m_ctrlPanel, wxID_ANY, wxXmlResource::Get()->LoadBitmap(wxT("control_fullscreen")), wxDefaultPosition, wxSize(-1,-1), wxBU_AUTODRAW);
    
    gridSizer16->Add(m_toggleVideoButton, 0, wxALL, 5);
    
    boxSizer30->Add(0, 0, 1, wxALL, 5);
    
    m_volumeCtrl = new wxSlider(m_ctrlPanel, wxID_ANY, 0, 0, 100, wxDefaultPosition, wxSize(-1,-1), wxSL_HORIZONTAL);
    
    boxSizer30->Add(m_volumeCtrl, 1, wxALL|wxALIGN_CENTER_VERTICAL, 5);
    
    
    SetSizeHints(500,90);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
    // Connect events
    this->Connect(wxEVT_LEAVE_WINDOW, wxMouseEventHandler(VideoCtrlPopupBase::OnLeaveWindow), NULL, this);
    m_positionctrl->Connect(wxEVT_SCROLL_CHANGED, wxScrollEventHandler(VideoCtrlPopupBase::OnPositionChanged), NULL, this);
    m_previousButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnPrevious), NULL, this);
    m_playPauseButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnPlayPause), NULL, this);
    m_stopButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnStop), NULL, this);
    m_nextButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnNext), NULL, this);
    m_toggleVideoButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnFullVideoToggle), NULL, this);
    m_volumeCtrl->Connect(wxEVT_SCROLL_CHANGED, wxScrollEventHandler(VideoCtrlPopupBase::OnVolumeChanged), NULL, this);
    m_volumeCtrl->Connect(wxEVT_SCROLL_THUMBTRACK, wxScrollEventHandler(VideoCtrlPopupBase::OnVolumeChanged), NULL, this);
    
}

VideoCtrlPopupBase::~VideoCtrlPopupBase()
{
    this->Disconnect(wxEVT_LEAVE_WINDOW, wxMouseEventHandler(VideoCtrlPopupBase::OnLeaveWindow), NULL, this);
    m_positionctrl->Disconnect(wxEVT_SCROLL_CHANGED, wxScrollEventHandler(VideoCtrlPopupBase::OnPositionChanged), NULL, this);
    m_previousButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnPrevious), NULL, this);
    m_playPauseButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnPlayPause), NULL, this);
    m_stopButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnStop), NULL, this);
    m_nextButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnNext), NULL, this);
    m_toggleVideoButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VideoCtrlPopupBase::OnFullVideoToggle), NULL, this);
    m_volumeCtrl->Disconnect(wxEVT_SCROLL_CHANGED, wxScrollEventHandler(VideoCtrlPopupBase::OnVolumeChanged), NULL, this);
    m_volumeCtrl->Disconnect(wxEVT_SCROLL_THUMBTRACK, wxScrollEventHandler(VideoCtrlPopupBase::OnVolumeChanged), NULL, this);
    
}
